#!/usr/bin/env python3
import argparse
import json
import os
import re
import subprocess
from pathlib import Path


def run(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        raise RuntimeError(p.stderr.strip() or p.stdout.strip() or f"command failed: {' '.join(cmd)}")
    return p.stdout


def parse_vtt(vtt_text: str):
    entries = []
    cue_re = re.compile(r"(\d{2}:\d{2}:\d{2}\.\d{3})\s+-->\s+(\d{2}:\d{2}:\d{2}\.\d{3})")
    lines = vtt_text.splitlines()
    i = 0
    while i < len(lines):
        m = cue_re.search(lines[i])
        if not m:
            i += 1
            continue
        start = m.group(1)
        end = m.group(2)
        i += 1
        txt = []
        while i < len(lines) and lines[i].strip():
            t = re.sub(r"<[^>]+>", "", lines[i]).strip()
            if t:
                txt.append(t)
            i += 1
        text = re.sub(r"\s+", " ", " ".join(txt)).strip()
        if text:
            entries.append({"start": start, "end": end, "text": text})
    return entries


def hms_to_seconds(hms: str) -> float:
    hh, mm, ss = hms.split(":")
    return int(hh) * 3600 + int(mm) * 60 + float(ss)


def pick_caption_file(folder: Path):
    cands = sorted(folder.glob("*.vtt"))
    # prefer manual en, fallback auto
    priorities = [
        lambda p: ".en." in p.name and ".live_chat" not in p.name,
        lambda p: "en" in p.name,
        lambda p: True,
    ]
    for pred in priorities:
        for c in cands:
            if pred(c):
                return c
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True)
    ap.add_argument("--out-dir", default="./artifacts")
    args = ap.parse_args()

    out = Path(args.out_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    # Fetch metadata JSON and subtitles
    # Writes subtitle files and metadata sidecar
    cmd = [
        "yt-dlp",
        "--skip-download",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs",
        "en.*,en",
        "--sub-format",
        "vtt",
        "--write-info-json",
        "-o",
        str(out / "video.%(ext)s"),
        args.url,
    ]
    run(cmd)

    info_files = sorted(out.glob("video.info.json"))
    if not info_files:
        info_files = sorted(out.glob("*.info.json"))
    if not info_files:
        raise RuntimeError("No metadata file generated by yt-dlp.")

    info = json.loads(info_files[0].read_text())
    cap = pick_caption_file(out)
    if not cap:
        raise RuntimeError("No captions found (manual or auto).")

    entries = parse_vtt(cap.read_text(errors="ignore"))
    if not entries:
        raise RuntimeError("Caption file found but no transcript entries parsed.")

    transcript = {
        "source_url": args.url,
        "title": info.get("title", ""),
        "uploader": info.get("uploader", ""),
        "duration": info.get("duration", 0),
        "webpage_url": info.get("webpage_url", args.url),
        "description": info.get("description", ""),
        "caption_file": str(cap),
        "entries": entries,
    }

    out_json = out / "transcript.json"
    out_json.write_text(json.dumps(transcript, indent=2))
    print(str(out_json))


if __name__ == "__main__":
    main()
