#!/usr/bin/env python3
import argparse
import re
from pathlib import Path

VALID_RESOURCES = {"scripts", "references", "assets"}


def slugify(name: str) -> str:
    s = name.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s[:64]


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def create_skill(args):
    skill_name = slugify(args.name)
    if not skill_name:
        raise SystemExit("Invalid --name after normalization.")
    if not args.description.strip():
        raise SystemExit("--description is required.")

    out_dir = Path(args.output_dir).expanduser().resolve() / skill_name
    if out_dir.exists() and not args.force:
        raise SystemExit(f"Skill path already exists: {out_dir}. Use --force to overwrite.")

    if out_dir.exists() and args.force:
        # conservative: only remove files inside skill dir
        for p in sorted(out_dir.rglob("*"), reverse=True):
            if p.is_file() or p.is_symlink():
                p.unlink(missing_ok=True)
            elif p.is_dir():
                p.rmdir()

    out_dir.mkdir(parents=True, exist_ok=True)

    resources = set()
    if args.resources:
        for r in [x.strip() for x in args.resources.split(",") if x.strip()]:
            if r not in VALID_RESOURCES:
                raise SystemExit(f"Invalid resource: {r}. Allowed: {', '.join(sorted(VALID_RESOURCES))}")
            resources.add(r)

    skill_md = f"""---
name: {skill_name}
description: {args.description.strip()}
---

# {skill_name}

## Workflow

1. Accept input request.
2. Validate required inputs.
3. Execute deterministic steps.
4. Return concise output.

## Input contract

- Required:
  - <define required inputs>
- Optional:
  - <define optional inputs>

## Output contract

- Return <format> with:
  - <field1>
  - <field2>

## Edge cases

- Missing required input
- Empty result set
- External tool failure
"""
    write(out_dir / "SKILL.md", skill_md)

    if args.with_readme:
        readme = f"""# {skill_name}

Generated by skill-creator.

## Quick start

- Edit `SKILL.md` to finalize triggering description and workflow.
- Add scripts/references/assets if needed.
- Package skill when ready.

## Suggested validation checklist

- [ ] Frontmatter has only `name` and `description`
- [ ] Description clearly states when to use the skill
- [ ] Instructions are concise and imperative
"""
        write(out_dir / "README.md", readme)

    for r in sorted(resources):
        (out_dir / r).mkdir(parents=True, exist_ok=True)

    if args.with_examples:
        if "references" in resources:
            ex = """# Patterns

## Good input/output pattern
- Input: clear params
- Output: deterministic schema

## Error handling pattern
- Return explicit error reason and next action
"""
            write(out_dir / "references" / "patterns.md", ex)

        if "scripts" in resources:
            helper = """#!/usr/bin/env bash
set -euo pipefail

echo \"helper script placeholder\"\n"""
            write(out_dir / "scripts" / "helper.sh", helper)
            (out_dir / "scripts" / "helper.sh").chmod(0o755)

    print(f"Created skill scaffold: {out_dir}")
    print("Next:")
    print(f"  ls -la {out_dir}")
    print(f"  sed -n '1,120p' {out_dir / 'SKILL.md'}")


def main():
    p = argparse.ArgumentParser(description="Create a new skill scaffold")
    p.add_argument("--name", required=True, help="Skill name (human text allowed)")
    p.add_argument("--description", required=True, help="One-line skill purpose/trigger")
    p.add_argument("--output-dir", default="~/.openclaw/workspace/skills", help="Base directory for skills")
    p.add_argument("--resources", default="scripts,references", help="Comma list: scripts,references,assets")
    p.add_argument("--with-examples", action="store_true")
    p.add_argument("--with-readme", action="store_true")
    p.add_argument("--force", action="store_true")
    args = p.parse_args()
    create_skill(args)


if __name__ == "__main__":
    main()
